# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 13:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-c_time'], 'verbose_name': 'Asset summary statement', 'verbose_name_plural': 'Asset summary statements'},
        ),
        migrations.AlterModelOptions(
            name='businessunit',
            options={'verbose_name': 'Line of business', 'verbose_name_plural': 'Line of businesses'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Contract', 'verbose_name_plural': 'Contracts'},
        ),
        migrations.AlterModelOptions(
            name='disk',
            options={'verbose_name': 'Disk', 'verbose_name_plural': 'Disks'},
        ),
        migrations.AlterModelOptions(
            name='eventlog',
            options={'verbose_name': 'Event log', 'verbose_name_plural': 'Event logs'},
        ),
        migrations.AlterModelOptions(
            name='idc',
            options={'verbose_name': 'IDC', 'verbose_name_plural': 'IDC'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Manufacturer', 'verbose_name_plural': 'Manufacturers'},
        ),
        migrations.AlterModelOptions(
            name='networkdevice',
            options={'verbose_name': 'Network device', 'verbose_name_plural': 'Network devices'},
        ),
        migrations.AlterModelOptions(
            name='newassetapprovalzone',
            options={'ordering': ['-c_time'], 'verbose_name': 'New online to approve asset', 'verbose_name_plural': 'New online to approve assets'},
        ),
        migrations.AlterModelOptions(
            name='nic',
            options={'verbose_name': 'NIC', 'verbose_name_plural': 'NIC'},
        ),
        migrations.AlterModelOptions(
            name='ram',
            options={'verbose_name': 'RAM', 'verbose_name_plural': 'RAM'},
        ),
        migrations.AlterModelOptions(
            name='securitydevice',
            options={'verbose_name': 'Security device', 'verbose_name_plural': 'Security devices'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name': 'Server', 'verbose_name_plural': 'Servers'},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'verbose_name': 'Software/OS', 'verbose_name_plural': 'Software/OS'},
        ),
        migrations.AlterModelOptions(
            name='storagedevice',
            options={'verbose_name': 'Storage device', 'verbose_name_plural': 'Storage devices'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL, verbose_name='Asset admin'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to=settings.AUTH_USER_MODEL, verbose_name='Approver'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('server', 'Server'), ('networkdevice', 'Network device'), ('storagedevice', 'Storage device'), ('securitydevice', 'Security device'), ('software', '\u8f6f\u4ef6\u8d44\u4ea7')], default='server', max_length=64, verbose_name='Asset type'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.BusinessUnit', verbose_name='Business unit'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Approval date'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Contract', verbose_name='Contract'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='expire_day',
            field=models.DateField(blank=True, null=True, verbose_name='Expire day'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.IDC', verbose_name='IDC'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='m_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Modify date'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='manage_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Manage IP'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='Memo'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Asset name'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_day',
            field=models.DateField(blank=True, null=True, verbose_name='Purchase day'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='sn',
            field=models.CharField(max_length=128, unique=True, verbose_name='Asset serial number'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Online'), (1, 'Offline'), (2, 'Unknown'), (3, 'Breakdown'), (4, 'Spare')], default=0, verbose_name='Device status'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(blank=True, to='assets.Tag', verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='memo',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Memo'),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Line of business'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='c_day',
            field=models.DateField(auto_now_add=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='detail',
            field=models.TextField(blank=True, null=True, verbose_name='Contract detail'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_day',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='license_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='License number'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='m_day',
            field=models.DateField(auto_now=True, verbose_name='Modify date'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='Memo'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Contract name'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='price',
            field=models.IntegerField(verbose_name='Contract price'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sn',
            field=models.CharField(max_length=128, unique=True, verbose_name='Contract number'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_day',
            field=models.DateField(blank=True, null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cpu_core_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='CPU core count'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cpu_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='CPU count'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cpu_model',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='CPU model'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='capacity',
            field=models.FloatField(blank=True, null=True, verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='interface_type',
            field=models.CharField(choices=[('SATA', 'SATA'), ('SAS', 'SAS'), ('SCSI', 'SCSI'), ('SSD', 'SSD'), ('unknown', 'unknown')], default='unknown', max_length=16, verbose_name='Interface type'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Disk manufacturer'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='model',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Disk model'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='slot',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Location of the slot'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='sn',
            field=models.CharField(max_length=128, verbose_name='Disk serial number'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='component',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Event subitem'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Event date'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='detail',
            field=models.TextField(verbose_name='Event detail'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='event_type',
            field=models.SmallIntegerField(choices=[(0, 'other'), (1, 'Hardware change'), (2, 'Add accessory'), (3, 'Device offline'), (4, 'Device online'), (5, 'Serviced regularly'), (6, 'Business online/update/modify')], default=4, verbose_name='Event type'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='Memo'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Event name'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Event executor'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='memo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Memo'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='IDC name'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='memo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Memo'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Manufacturer name'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Support telephone'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='device_detail',
            field=models.TextField(blank=True, null=True, verbose_name='Detailed configuration'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='firmware',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Device firmware edition'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='intranet_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Intranet IP'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='model',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Network device model'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='port_num',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Port number'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='sub_asset_type',
            field=models.SmallIntegerField(choices=[(0, 'Router'), (1, 'Switches'), (2, 'Load balancing'), (4, 'VPN device')], default=0, verbose_name='Network device type'),
        ),
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Whether or not to approve'),
        ),
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='asset_type',
            field=models.CharField(blank=True, choices=[('server', 'Server'), ('networkdevice', 'Network device'), ('storagedevice', 'Storage device'), ('securitydevice', 'Security device'), ('IDC', 'IDC'), ('software', 'Asset software')], default='server', max_length=64, null=True, verbose_name='Asset type'),
        ),
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Report date'),
        ),
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='cpu_core_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='CPU core count'),
        ),
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='cpu_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='CPU count'),
        ),
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='cpu_model',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='CPU model'),
        ),
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='data',
            field=models.TextField(verbose_name='Asset data'),
        ),
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='m_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Data modify date'),
        ),
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='model',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='os_distribution',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='OS distribution'),
        ),
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='os_release',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='OS release'),
        ),
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='os_type',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='OS type'),
        ),
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='ram_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='RAM size'),
        ),
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='sn',
            field=models.CharField(max_length=128, unique=True, verbose_name='Asset serial number'),
        ),
        migrations.AlterField(
            model_name='nic',
            name='bonding',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Bonding address'),
        ),
        migrations.AlterField(
            model_name='nic',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='nic',
            name='mac',
            field=models.CharField(max_length=64, verbose_name='Mac address'),
        ),
        migrations.AlterField(
            model_name='nic',
            name='model',
            field=models.CharField(max_length=128, verbose_name='NIC model'),
        ),
        migrations.AlterField(
            model_name='nic',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='NIC name'),
        ),
        migrations.AlterField(
            model_name='nic',
            name='net_mask',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Net mask'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='RAM manufacturer'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='model',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='RAM model'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='slot',
            field=models.CharField(max_length=64, verbose_name='Slot'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='sn',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Serial number'),
        ),
        migrations.AlterField(
            model_name='securitydevice',
            name='sub_asset_type',
            field=models.SmallIntegerField(choices=[(0, 'Fire wall'), (1, 'Intrusion detection device'), (2, 'Internet gateway'), (4, 'SSA')], default=0, verbose_name='Security device type'),
        ),
        migrations.AlterField(
            model_name='server',
            name='created_by',
            field=models.CharField(choices=[('auto', 'Automatically add'), ('manual', 'Manual input')], default='auto', max_length=32, verbose_name='Add mode'),
        ),
        migrations.AlterField(
            model_name='server',
            name='hosted_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_on_server', to='assets.Server', verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='server',
            name='model',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Server model'),
        ),
        migrations.AlterField(
            model_name='server',
            name='os_distribution',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='OS distribution'),
        ),
        migrations.AlterField(
            model_name='server',
            name='os_release',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='OS release'),
        ),
        migrations.AlterField(
            model_name='server',
            name='os_type',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='OS type'),
        ),
        migrations.AlterField(
            model_name='server',
            name='raid_type',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Raid type'),
        ),
        migrations.AlterField(
            model_name='server',
            name='sub_asset_type',
            field=models.SmallIntegerField(choices=[(0, 'PC Server'), (1, 'Blade'), (2, 'Minicomputer')], default=0, verbose_name='Server type'),
        ),
        migrations.AlterField(
            model_name='software',
            name='license_num',
            field=models.IntegerField(default=1, verbose_name='License number'),
        ),
        migrations.AlterField(
            model_name='software',
            name='sub_asset_type',
            field=models.SmallIntegerField(choices=[(0, 'OS'), (1, 'Office/Development software'), (2, 'Business software')], default=0, verbose_name='Software type'),
        ),
        migrations.AlterField(
            model_name='software',
            name='version',
            field=models.CharField(help_text='\u4f8b\u5982: CentOS release 6.7 (Final)', max_length=64, unique=True, verbose_name='Software/OS release'),
        ),
        migrations.AlterField(
            model_name='storagedevice',
            name='sub_asset_type',
            field=models.SmallIntegerField(choices=[(0, 'Disk array'), (1, 'Network memorizer'), (2, 'Tape library'), (4, 'Tape streamer')], default=0, verbose_name='Storage device type'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='c_day',
            field=models.DateField(auto_now_add=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Tag name'),
        ),
    ]
