# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-16 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_software_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('server', 'Server'), ('networkdevice', 'Network device'), ('storagedevice', 'Storage device'), ('securitydevice', 'Security device'), ('software', 'Asset software')], default='server', max_length=64, verbose_name='Asset type'),
        ),
    ]
