# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-16 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-c_time'], 'verbose_name': 'User profile', 'verbose_name_plural': 'User profiles'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create date'),
            preserve_default=False,
        ),
    ]
